<a href="https://colab.research.google.com/github/adarshnitt/Deep-Learning/blob/main/elements_in_tf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# elemts in tensorflow
# shift+tab: put cursor over function, shift+tab will give documentation about that function
# shift+enter: run the notebook

<h1> Constant </h1>

In [1]:
# constant: create a constant for tensor like object.
import tensorflow as tf 
cons1=tf.constant(10)
# note: if a tensor is created u cant be able to alter it

In [3]:
tf.__version__ # __version__ to check version of any python 

'2.7.0'

In [4]:
tf.test.is_gpu_available() # to check if gpu is available or not

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

In [5]:
tf.test?

In [6]:
tf.constant(12.0) # we cannot modify its value ater.
#show putput below
#tf.contant(value,dtype,shape)

<tf.Tensor: shape=(), dtype=float32, numpy=12.0>

In [7]:
tf.constant([1,2,3] ) # see log

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [9]:
import numpy as np #
np_array=tf.constant(np.array([1,2,3])) #np.array is def for array formation 

In [10]:
np.array([1,2,3])

array([1, 2, 3])

In [13]:
# method-1 for 2d tensor
twod_array=tf.constant(np.array([[1,2],[2,3]]))
twod_array # 2d tensor

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[1, 2],
       [2, 3]])>

In [18]:
print(twod_array.shape,"-----",twod_array.dtype)

(2, 2) ----- <dtype: 'int64'>


In [19]:
# to get exact value of tensor
twod_array.numpy()

array([[1, 2],
       [2, 3]])

In [20]:
# to get exact value of tensor with index
twod_array.numpy()[1]

array([2, 3])

In [14]:
# method-2 for 2d tensor
tf.constant([1,2,3,4],shape=[2,2])

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [15]:
 # method-2 for 2d tensor with float dtype
tf.constant([1,2,3,4],shape=[2,2], dtype="float64")

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1., 2.],
       [3., 4.]])>

In [16]:
# N-dimentional array
tf.constant(np.array([[[1],[2]]]))

<tf.Tensor: shape=(1, 2, 1), dtype=int64, numpy=
array([[[1],
        [2]]])>

In [17]:
# N-dimentional array
tf.constant([1,2,3],shape=[1,1,3])

<tf.Tensor: shape=(1, 1, 3), dtype=int32, numpy=array([[[1, 2, 3]]], dtype=int32)>

In [36]:
# complex data type: use j for imaginary part-'j'
tf.constant([1+3j])

<tf.Tensor: shape=(1,), dtype=complex128, numpy=array([1.+3.j])>

<h1> Variables ------------
</h

In [21]:
# variables: allow us to new variable parameter in graph(tensorflow)
var1=tf.Variable(2)

'''initial value defines the type and shape of the variable. 
After construction, the type and shape of the variable are fixed. The value can be changed'''

'initial value defines the type and shape of the variable. \nAfter construction, the type and shape of the variable are fixed. The value can be changed'

In [25]:
var1=tf.Variable([1,2,3]) # press shift+tab for more documentation

In [27]:
var1.shape

TensorShape([3])

In [28]:
var1.dtype

tf.int32

In [29]:
var1.numpy() # converting data into numpy array

array([1, 2, 3], dtype=int32)

In [30]:
type(var1)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [33]:
var2=tf.Variable([1,2,3.0])
var2

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [34]:
var3=tf.Variable(["a","b","c"])
var3

<tf.Variable 'Variable:0' shape=(3,) dtype=string, numpy=array([b'a', b'b', b'c'], dtype=object)>

In [39]:
# complex datatype
tf.Variable([1+2j])

<tf.Variable 'Variable:0' shape=(1,) dtype=complex128, numpy=array([1.-2.j])>

In [42]:
# variable tensor generation using constant tensor.
c1=tf.constant([12])
v_derived=tf.Variable(c1)

In [44]:
# varivble with different shape
tf.Variable([[1,2],[3,4]])

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [51]:
# reshaping an existing variable
v1=tf.Variable([1,2,3,4,5,9])
v2=tf.reshape(v1,[2,3])
v2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 9]], dtype=int32)>

In [55]:
# get index of highest value
index=tf.argmax(v2).numpy()
index

array([1, 1, 1])

In [57]:
# convert to tensor
n1=np.array([1,2,3])
tf.convert_to_tensor(n1)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

In [60]:
# assign a new value in tensor, in variable, shape and dtype will be same but value can be chyange
x=tf.Variable([1,2,3])
x.assign( [111,222,333]).numpy()

array([111, 222, 333], dtype=int32)

In [62]:
# assign same variable with new memory
x=tf.Variable([1,2,3])
x.assign_add([9,9,9])  # allotted new memory location(new_value must be same data and same data type)

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([10, 11, 12], dtype=int32)>

Placeholder
<br>
type of variable and used to assign data at later stage.

In [1]:
import tensorflow as tf

In [4]:
p1=tf.compat.v1.placeholder()
#tf.compat: aloow code  to work in many versions.
# tf.compat.v1, tf.compat.v2       ,version1 and version 2.

TypeError: ignored

In [5]:
tf.placeholder(dtype=tf.float32,shape=(20,20))
# i will get error bcz in v2, there is no such thing like placeholder

AttributeError: ignored

In [8]:
# solution of above error
tf.compat.v1.placeholder(dtype=tf.float32,shape=(20,20))
# now again error will come saying that eager execution is not supportable.

RuntimeError: ignored

In [9]:
# actually in tf, all code implemented qucikly, eagerly executed.
# we will postpone eager execution
tf.compat.v1.disable_eager_execution()

In [12]:
p1=tf.compat.v1.placeholder(dtype=tf.uint64, shape=(20,20))
# now place holder will create after resusing eager execution.
p1 

<tf.Tensor 'Placeholder_2:0' shape=(20, 20) dtype=uint64>

In [14]:
# place holder is used to stor data in future
p2=tf.compat.v1.placeholder(dtype=tf.uint64, shape=(20,20))
p2

<tf.Tensor 'Placeholder_4:0' shape=(20, 20) dtype=uint64>

In [16]:
# arithmatic operation using placeholder
out1=tf.add(p1,p2)  # press shift+tab for more info
out1 # formed a graph

<tf.Tensor 'Add:0' shape=(20, 20) dtype=uint64>

In [19]:
# data prep for placeholders
import numpy as np
d1=np.ones(shape=(20,20),dtype=np.uint64)

In [ ]:
# execution and stopping execution are available only in tensorflow 1
# so we need to run "session" for things in tensorflow 1.x

In [25]:
# execute tensorflow palceholder with sessions
with tf.compat.v1.Session() as sess:
  result=sess.run(out1,feed_dict={p1:d1,p2:d1})

In [26]:
result

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2,

<h1> Sparse and dense Tensor</h1>

In [32]:
# sparse : contain lot of zeros
s1=tf.SparseTensor(indices=[[1,2],[2,2]],values=[11,22],dense_shape=[2,2]) 
# indices: at which cordinates things will not be sparse and its respective values
s1

In [36]:
print(s1)

SparseTensor(indices=Tensor("SparseTensor_1/indices:0", shape=(2, 2), dtype=int64), values=Tensor("SparseTensor_1/values:0", shape=(2,), dtype=int32), dense_shape=Tensor("SparseTensor_1/dense_shape:0", shape=(2,), dtype=int64))


In [52]:
# covert a dense into sparse
a=np.array([[1,0],
            [0,1]])
out=tf.sparse.from_dense(a)

In [55]:
# indices of sparce tensor where non 0
print(out.indices)

Tensor("dense_to_sparse_2/Where:0", shape=(None, 2), dtype=int64)


In [59]:
# sparse to dense
dense1=tf.sparse.to_dense(s1)
dense1

<tf.Tensor 'SparseToDense_3:0' shape=(2, 2) dtype=int32>

In [63]:
tf.config.run_functions_eagerly(True)
dense1.numpy()

AttributeError: ignored

In [68]:
ad=tf.sparse.add(s1,s1)
print(ad)

SparseTensor(indices=Tensor("SparseAdd_4:0", shape=(None, 2), dtype=int64), values=Tensor("SparseAdd_4:1", shape=(None,), dtype=int32), dense_shape=Tensor("SparseTensor_6/dense_shape:0", shape=(2,), dtype=int64))


# ones vs ones_like vs Ones_initializer

In [82]:
# tf.ones(): all elemets with given shape and dtype will be one
o1=tf.ones(shape=(10,10),dtype=tf.float32)
o1

<tf.Tensor 'ones_2:0' shape=(10, 10) dtype=float32>

In [85]:
o2=tf.ones(shape=(2,3,4),dtype=tf.float32)
print(o2)

Tensor("ones_5:0", shape=(2, 3, 4), dtype=float32)


In [ ]:
# ones_like() :  create a tensor of ones same as "shape of given input"
#only dtata known, no  shape is known.
# create tensor like same as given data.

In [87]:
# creating a sample data for ones_like
c1=tf.constant([[9,8,800,78]])

In [89]:
same1=tf.ones_like(c1,dtype=tf.int32) # create ones array of given shape input with our decided dtype.
same1  # shape is same as input

<tf.Tensor 'ones_like_1:0' shape=(1, 4) dtype=int32>

In [91]:
tf.ones_like(same1,dtype=tf.float32)

<tf.Tensor 'ones_like_3:0' shape=(1, 4) dtype=float32>

In [96]:
# generate sample data
d1=tf.Variable([9,7,5],dtype=tf.int64)
same2=tf.ones_like(d1,dtype=tf.float32)
same2

<tf.Tensor 'ones_like_5:0' shape=(3,) dtype=float32>

In [ ]:
# ones_initializer() # this time neither shape nor type also know
# provide a data with shape of given input and type of given input


In [97]:
#m-1
def one_init(shape,dtype,initlizer):
  return tf.Variable(initlizer(shape,dtype))

In [100]:
one_init_exam=one_init((2,2),tf.float32,tf.ones_initializer())
one_init_exam
 # note it will return tf.Variable not ki tf.tensor

<tf.Variable 'Variable_6:0' shape=(2, 2) dtype=float32>

In [120]:
#m-2
tf.Variable(tf.ones_initializer()(shape=(2,2),dtype=tf.bool))

<tf.Variable 'Variable_10:0' shape=(2, 2) dtype=bool>

In [121]:
tf.zerod_initializer() 
# initializer took no arguments.

AttributeError: ignored

In [ ]:
# tf.ones: generate nay tensor with known shape and dtype
# tf.one_like(): generate tensor with known dtype. shape will get from known input data
# tf.ones_initializer() : whith unknown shape and data. everything will get from input data.
     # pre initialization tech, without known 

<h1> Zeros vs Zeros_like vs Zeros_initializer </h1>

In [ ]:
# tf.zeros() :  everything known
#create a tensor with all elemetvto zero

In [102]:
z1=tf.zeros(shape=(2,3),dtype=tf.float32)
z1

<tf.Tensor 'zeros_7:0' shape=(2, 3) dtype=float32>

In [ ]:
tf.zeros() # press shift+tab, to know about function 

In [ ]:
# tf.zeros_like():   data shape is unknown.
# a tensor with all elemt to zero

In [105]:
x=tf.zeros(shape=(1,2,4),dtype=tf.float32)
x.shape

TensorShape([1, 2, 4])

In [107]:
# tf.zero_like()  # shape will dedtermine through input data.
# input data ki  tarah banao.
# set all elemest set to zero

In [108]:
# generating sample data
c1=tf.constant([1,2,3])

In [109]:
# tf.zeros_like
z1=tf.zeros_like(c1,dtype=tf.float32)

In [113]:
tf.zeros_like(c1, dtype=tf.bool)

<tf.Tensor 'zeros_like_2:0' shape=(3,) dtype=bool>

In [110]:
# zeros_initializer: neither know shape nor dtype.
# generate data like same as input data
# helps to define a pre initialization strategy without knowing shape and dtype of variable initialized.
var1=tf.Variable([1,2,3,4])

In [118]:
# m-1
def f1(shape, dtype, inite):
  "initialize with given shape and dtype"
  return tf.Variable(inite(shape,dtype=dtype))

In [116]:
f1((2,2),tf.float32,tf.zeros_initializer())

<tf.Variable 'Variable_8:0' shape=(2, 2) dtype=float32>

In [117]:
tf.zeros_initializer()

In [119]:
# m-2
tf.Variable(tf.zeros_initializer()((2,2),dtype=tf.int32))

<tf.Variable 'Variable_9:0' shape=(2, 2) dtype=int32>