<a href="https://colab.research.google.com/github/adarshnitt/Deep-Learning/blob/main/Mathmatics_In_Tf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [5]:
v=tf.constant([9,80])
v.numpy()

array([ 9, 80], dtype=int32)

In [10]:
# addition
a=90
b=89
tf.add(a,b).numpy()

179

In [14]:
# adding a list
a=[1,2,3]
b=[22,33,4]
tf.add(a,b).numpy()

array([23, 35,  7], dtype=int32)

In [16]:
# add 2 tuple
a=(1,2,3)
b=(22,3,4)
tf.add(a,b).numpy()

array([23,  5,  7], dtype=int32)

In [18]:
# list +tup[le
tf.add([1,2,3],(1,23,4)).numpy()

array([ 2, 25,  7], dtype=int32)

In [20]:
#**********************************************************************
# if differnt shapes then either must be singleton
tf.add([1,2,3],3).numpy()

array([4, 5, 6], dtype=int32)

In [21]:
tf.add([1,2,3],[3]).numpy()

array([4, 5, 6], dtype=int32)

In [23]:
tf.add([1,2,3],[[[3]]]).numpy() # either must be singleton if shape unequal

array([[[4, 5, 6]]], dtype=int32)

In [24]:
c1=tf.constant([1,2,3])
tf.add(c1,2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 4, 5], dtype=int32)>

In [50]:
#*************************
import numpy as np
# 2 numpy array with different shape but same length
x= np.ones(6).reshape(1,2,3,1)
y= np.ones(6).reshape(2,1,3)
tf.add(x,y) # 


<tf.Tensor: shape=(1, 2, 3, 3), dtype=float64, numpy=
array([[[[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]]]])>

Substract

In [38]:
a=90
b=67
tf.subtract(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=23>

In [39]:
x=[9,7,8]
y=[88,99,8]
tf.subtract(x,y)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-79, -92,   0], dtype=int32)>

In [41]:
x=[9,7,8]
y=[88]
tf.subtract(x,y)  # if shape differ, atleast 1 element hona chaiye

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-79, -81, -80], dtype=int32)>

In [42]:
x=(9,7,8)
y=(88,99,8)
tf.subtract(x,y)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-79, -92,   0], dtype=int32)>

In [43]:
x=[9,7,8]
y=8
tf.subtract(x,y)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 1, -1,  0], dtype=int32)>

In [47]:
#*****************************************
x=np.ones(6).reshape(2,1,3,1)
y=np.ones(6).reshape(1,6,1,1)
tf.subtract(x,y)

<tf.Tensor: shape=(2, 6, 3, 1), dtype=float64, numpy=
array([[[[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]]]])>

Multiplications


In [51]:
# multiply elremt wise
a=[1,2,3]
b=[2,3,4]
tf.multiply(a,b).numpy()

array([ 2,  6, 12], dtype=int32)

In [53]:
a=[1,2,3]
b=[2]
tf.multiply(a,b).numpy()

array([2, 4, 6], dtype=int32)

In [54]:
a=[1,2,3]
b=2
tf.multiply(a,b).numpy()

array([2, 4, 6], dtype=int32)

In [55]:
a=(1,2,3)
b=(2,3,4)
tf.multiply(a,b).numpy()

array([ 2,  6, 12], dtype=int32)

In [59]:
# ******************************************
a=np.array([1,2,3]).reshape(3,1,1)  #  no of elemwnt can be same, shape alter
b=np.array([2,3,4]).reshape(1,3)
tf.multiply(a,b)

<tf.Tensor: shape=(3, 1, 3), dtype=int64, numpy=
array([[[ 2,  3,  4]],

       [[ 4,  6,  8]],

       [[ 6,  9, 12]]])>

In [63]:
a=np.array([1,2,3]).reshape(3,1,1,1) # out shape will be max of both individual direction: 3,3,1,1
b=np.array([2,3,4]).reshape(1,3,1,1)
tf.multiply(a,b)

<tf.Tensor: shape=(3, 3, 1, 1), dtype=int64, numpy=
array([[[[ 2]],

        [[ 3]],

        [[ 4]]],


       [[[ 4]],

        [[ 6]],

        [[ 8]]],


       [[[ 6]],

        [[ 9]],

        [[12]]]])>

<h1>division</h1>


In [64]:
# elemt wise division
a=1
b=5
tf.divide(a,b)

<tf.Tensor: shape=(), dtype=float64, numpy=0.2>

In [66]:
a=1
b=0
tf.divide(a,b).numpy()

inf

In [67]:
a=[2.,4,5]
b=[1,2,3]
tf.divide(a,b).numpy()

array([2.       , 2.       , 1.6666666], dtype=float32)

In [70]:
8/2 

4.0

In [71]:
8//2 # how many times

4

In [72]:
8%2 # remainder

0

In [73]:
a=[1,2,3]
b=[6]
tf.divide(a,b).numpy()

array([0.16666667, 0.33333333, 0.5       ])

In [74]:
a=[1,2,3]
b=7
tf.divide(a,b).numpy()

array([0.14285714, 0.28571429, 0.42857143])

In [76]:
a=(6,2,3)
b=(6)
tf.divide(a,b).numpy()

array([1.        , 0.33333333, 0.5       ])

In [77]:
a=np.array([1,2,3]).reshape(1,3) # result shape will be max of indivisual direction
b=np.array([4,6,7]).reshape(3,1)
tf.divide(a,b).numpy()

array([[0.25      , 0.5       , 0.75      ],
       [0.16666667, 0.33333333, 0.5       ],
       [0.14285714, 0.28571429, 0.42857143]])

<h1>**sqrt**</h1>


In [82]:
# it works only with float input. no int
tf.sqrt(23.9)
x=9.0
tf.sqrt(x)

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [83]:
x=[4,7]
tf.sqrt(x)

InvalidArgumentError: ignored

In [84]:
x=[4.0,7.0] # elememnts must be float, no int.
tf.sqrt(x)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.       , 2.6457512], dtype=float32)>

In [85]:
x=np.array([4.0,7.0]).reshape(1,1,2) # elememnts must be float, no int.
tf.sqrt(x)

<tf.Tensor: shape=(1, 1, 2), dtype=float64, numpy=array([[[2.        , 2.64575131]]])>

In [87]:
# tensor data ka
x=tf.convert_to_tensor([4.0,7.0]) # elememnts must be float, no int.
tf.sqrt(x).numpy()

array([2.       , 2.6457512], dtype=float32)

**pow**

In [92]:
x=[4,7]
tf.pow(x,3).numpy()

array([ 64, 343], dtype=int32)

In [93]:
x=[4,7]
y=x
tf.pow(x,y).numpy()

array([   256, 823543], dtype=int32)

In [95]:
x=[4,7]
tf.pow(tf.convert_to_tensor(x),3).numpy()

array([ 64, 343], dtype=int32)

**maximum**

In [99]:
# element wise comparison hoga
x=[4,7]
tf.maximum(x,x).numpy()

array([4, 7], dtype=int32)

In [100]:
x=[4,7]
tf.maximum(x,8).numpy()

array([8, 8], dtype=int32)

In [101]:
x=[4,7]
tf.maximum(x,[x]).numpy()

array([[4, 7]], dtype=int32)

minimum

In [102]:
# element wise comparison hoga
x=[4,7]
tf.minimum(x,x).numpy()

array([4, 7], dtype=int32)